### ISSUE TITLE
Improvement in footer and Home (size of icons)

### ISSUE THREAD

**Issue by DeepRahangdale** [nirmalyax/React-folio#12]
Increase the size of the icons nad font used in home and other sections.

**Comment by Thanush19** [comment]
i can fix this.. @DeepRahangdale

**Comment by nirmalyax** [comment]
You can move with the contributtion @Thanush19

**Comment by DeepRahangdale** [comment]
getting error while cloning your repository!!

**Comment by nirmalyax** [comment]
Can provide the screenshot please.

**Comment by DeepRahangdale** [comment]
(https://github.com/DeepRahangdale/React-folio/blob/main/error.png)

**Comment by nirmalyax** [comment]
Cloning steps
step 1
`cd "your directory"`
step 2
`git clone https://github.com/nirmalyax/React-folio.git`

it will be like this 

<img width="1440" alt="Screenshot 2023-10-14 at 11 40 02 PM" src="https://github.com/nirmalyax/React-folio/assets/35608135/a7ae959c-e87c-4fb2-9d71-2b9119fd0833">

**Comment by DeepRahangdale** [comment]
https://github.com/DeepRahangdale/React-folio/blob/main/error1.png

still getting the error

**Comment by nirmalyax** [comment]
`error is comming due to the signinsign up gif loacted in the assets folder `
So you can try forkig the repo and then clone or download the zip  after after all the required changes push it to your forked repo and then raise the merge req.

**Comment by DeepRahangdale** [comment]
getting the same error after forking and then cloning.. 
not even able to clone

**Comment by DeepRahangdale** [comment]
got it

**Comment by nirmalyax** [comment]
It might be beacuse of the naming `Signin:Signup.gif` windows can't handle this naming format so I changed it accordingly hope the ~`git clone` might work.
Can you give it a try.
