### ISSUE TITLE
Error in cloning the repo for Windows.

### ISSUE THREAD

**Issue by nirmalyax** [nirmalyax/React-folio#16]
Naming Signin:Signup.gif windows can't handle this naming format.

![error1](https://github.com/nirmalyax/React-folio/assets/35608135/16c56cdd-c279-44f7-95b1-127ef7940ac9)

**Comment by DeepRahangdale** [comment]
cd react-folio

**Comment by DeepRahangdale** [comment]
cd react-folio (your directory)
code .

Now Run the 'git restore --source=HEAD :/' in the Terminal Inside the Project Directory
Now all Files Inside the Project the file will be visible.
but will get the error after npm i and npm start.

 [Error: Can't resolve '../../assets/Signin:Signup.gif' in 'C:\Users\user1\React-folio\src\components\projects']
Signin/signup.gif is missing from the project.

**Comment by nirmalyax** [comment]
The `SigninSignup.gif` is already present in the right path
![Screenshot 2023-10-15 at 12 48 55 AM](https://github.com/nirmalyax/React-folio/assets/35608135/5d8a89e4-64ac-4967-8bf5-3fc7ba99e736)

**Comment by DeepRahangdale** [comment]
thanks for adding now the issue will be solved.

**Comment by nirmalyax** [comment]
After renaming the file `Signin:Signup.gif` to `SigninSignup.gif` the issue is fixed.
